1. Write a Pandas program to create and display a one-dimensional array using series  containing  even numbers upto 10000
#tip : use List Comprehension
#ds = pd.Series([0,2, 4, 6, 8..... 10000]) 

In [ ]:
import pandas as pd
ds = pd.Series([i for i in range(10001) if i%2 == 0]) 
print(ds)

0           0
1           2
2           4
3           6
4           8
        ...  
4996     9992
4997     9994
4998     9996
4999     9998
5000    10000
Length: 5001, dtype: int64


2. Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and  after convertion print its type 

In [ ]:
import pandas as pd
ds = pd.Series([i for i in range(1000,2001) if i%5 == 0])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("\n Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series and type
0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
196    1980
197    1985
198    1990
199    1995
200    2000
Length: 201, dtype: int64
<class 'pandas.core.series.Series'>

 Convert Pandas Series to Python list
[1000, 1005, 1010, 1015, 1020, 1025, 1030, 1035, 1040, 1045, 1050, 1055, 1060, 1065, 1070, 1075, 1080, 1085, 1090, 1095, 1100, 1105, 1110, 1115, 1120, 1125, 1130, 1135, 1140, 1145, 1150, 1155, 1160, 1165, 1170, 1175, 1180, 1185, 1190, 1195, 1200, 1205, 1210, 1215, 1220, 1225, 1230, 1235, 1240, 1245, 1250, 1255, 1260, 1265, 1270, 1275, 1280, 1285, 1290, 1295, 1300, 1305, 1310, 1315, 1320, 1325, 1330, 1335, 1340, 1345, 1350, 1355, 1360, 1365, 1370, 1375, 1380, 1385, 1390, 1395, 1400, 1405, 1410, 1415, 1420, 1425, 1430, 1435, 1440, 1445, 1450, 1455, 1460, 1465, 1470, 1475, 1480, 1485, 1490, 1495, 1500, 1505, 1510, 1515, 1520, 1525, 1530, 1535, 1540, 1545, 1550, 1555, 1560, 1565, 1570, 1575, 1580, 1585, 1590, 1595, 1600, 1605, 1610, 1615,

3. Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [ ]:
import pandas as pd
ds1 = pd.Series([i for i in range(2,101,2)])
ds2 = pd.Series([i for i in range(1,100,2)])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("\nSubtract two Series:")
ds = ds1 - ds2
print(ds)
print("\nMultiply two Series:")
ds = ds1 * ds2
print(ds)
print("\nDivide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0       3
1       7
2      11
3      15
4      19
5      23
6      27
7      31
8      35
9      39
10     43
11     47
12     51
13     55
14     59
15     63
16     67
17     71
18     75
19     79
20     83
21     87
22     91
23     95
24     99
25    103
26    107
27    111
28    115
29    119
30    123
31    127
32    131
33    135
34    139
35    143
36    147
37    151
38    155
39    159
40    163
41    167
42    171
43    175
44    179
45    183
46    187
47    191
48    195
49    199
dtype: int64

Subtract two Series:
0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
35    1
36    1
37    1
38    1
39    1
40    1
41    1
42    1
43    1
44    1
45    1
46    1
47    1
48    1
49    1
dtype: int64

Multiply two Series:
0        2
1  

4. Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
#Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]


In [ ]:
import pandas as pd
a = [i for i in range(1000) if i%7 == 0]
b = [i for i in range(1000) if i%11 == 0]
ds1 = pd.Series(a)
ds2 = pd.Series(b)
print("Series1:")
print(ds1)
print("\nSeries2:")
print(ds2)

if len(a) != len(b):
    if len(a)> len(b):
        a= a[:len(b)]
    else:
        b= b[:len(a)]
        
ds1 = pd.Series(a)
ds2 = pd.Series(b)
print("\nUpdated Series1:")
print(ds1)
print("\nUpdated Series2:")
print(ds2)
print("\nCompare the elements of the said Series:")
print("\nEquals:")
print(ds1 == ds2)
print("\nGreater than:")
print(ds1 > ds2)
print("\nLess than:")
print(ds1 < ds2)
print("\nNot Equals:")
print(ds1 != ds2)

Series1:
0        0
1        7
2       14
3       21
4       28
      ... 
138    966
139    973
140    980
141    987
142    994
Length: 143, dtype: int64

Series2:
0       0
1      11
2      22
3      33
4      44
     ... 
86    946
87    957
88    968
89    979
90    990
Length: 91, dtype: int64

Updated Series1:
0       0
1       7
2      14
3      21
4      28
     ... 
86    602
87    609
88    616
89    623
90    630
Length: 91, dtype: int64

Updated Series2:
0       0
1      11
2      22
3      33
4      44
     ... 
86    946
87    957
88    968
89    979
90    990
Length: 91, dtype: int64

Compare the elements of the said Series:

Equals:
0      True
1     False
2     False
3     False
4     False
      ...  
86    False
87    False
88    False
89    False
90    False
Length: 91, dtype: bool

Greater than:
0     False
1     False
2     False
3     False
4     False
      ...  
86    False
87    False
88    False
89    False
90    False
Length: 91, dtype: bool

Less than:
0  

5. Write a Pandas program to convert a NumPy array to a Pandas series. 
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]

In [ ]:
import numpy as np
import pandas as pd
np_array = np.array([i for i in range(10,1001,10)])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("\nConverted Pandas series:")
print(new_series)

NumPy array:
[  10   20   30   40   50   60   70   80   90  100  110  120  130  140
  150  160  170  180  190  200  210  220  230  240  250  260  270  280
  290  300  310  320  330  340  350  360  370  380  390  400  410  420
  430  440  450  460  470  480  490  500  510  520  530  540  550  560
  570  580  590  600  610  620  630  640  650  660  670  680  690  700
  710  720  730  740  750  760  770  780  790  800  810  820  830  840
  850  860  870  880  890  900  910  920  930  940  950  960  970  980
  990 1000]

Converted Pandas series:
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int32


6. Write a Pandas program to convert a given Series to an array.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [ ]:
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series: ")
print(s1)
print("\nSeries to an array: ")
a = np.array(s1.values.tolist())
print (a)

Original Data Series: 
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object

Series to an array: 
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


7. Write a Pandas program to sort a given Series.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [ ]:
import pandas as pd
s = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s)
print("\nSorted Series: ")
new_s = pd.Series(s).sort_values()
print(new_s)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object

Sorted Series: 
0          100
1          200
2          300
6       300.12
3          400
7          400
4          500
9        great
8           is
10    language
5       python
dtype: object


8. Write a Pandas program to create a subsets of a given series based on value and condition.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]
#value and condtion :  Subset 1 :numbers divisable by 7  Subset 2 : numbers divisable by 5

In [ ]:
import pandas as pd
s = pd.Series([i for i in range(10,1001,10)])
print("Original Data Series:")
print(s)
print("\nSubset 1 :numbers divisable by 7 :")
new_s1 = s[s%7==0]
print(new_s1)
print("\nSubset 2 :numbers divisable by 5 :")
new_s2 = s[s%5==0]
print(new_s2)

Original Data Series:
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int64

Subset 1 :numbers divisable by 7 :
6      70
13    140
20    210
27    280
34    350
41    420
48    490
55    560
62    630
69    700
76    770
83    840
90    910
97    980
dtype: int64

Subset 2 :numbers divisable by 5 :
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int64


9. Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [ ]:
import pandas as pd
import sympy
s = pd.Series(sympy.primerange(0, 1000))
print("Original Data Series:")
print(s)
print("\nMean of the Series:")
print(s.mean())
print("\nStandard deviation of the Series:")
print(s.std())
print("\nMaximum of the Series:")
print(s.max())
print("\nMinimum of the Series:")
print(s.min())

Original Data Series:
0        2
1        3
2        5
3        7
4       11
      ... 
163    971
164    977
165    983
166    991
167    997
Length: 168, dtype: int64

Mean of the Series:
453.13690476190476

Standard deviation of the Series:
298.19241719366255

Maximum of the Series:
997

Minimum of the Series:
2


10. Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}

In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[i if i%7 != 0 else "-" for i in range(1,1000,2)], 'Y':[i if i%5 != 0 else "-" for i in range(0,1000,2)],'Z':[i if i%3 != 0 else "-" for i in range(1,1000,2)]})
print(df)

       X    Y    Z
0      1    -    1
1      3    2    -
2      5    4    5
3      -    6    7
4      9    8    -
..   ...  ...  ...
495  991    -  991
496  993  992    -
497  995  994  995
498  997  996  997
499  999  998    -

[500 rows x 3 columns]


11. Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.

In [ ]:
import pandas as pd
df = pd.read_csv('movie_metadata.csv')
df[['movie_title','num_critic_for_reviews' ,'country']].head(10)

movie_title  num_critic_for_reviews  \
0                                            Avatar                    723.0   
1          Pirates of the Caribbean: At World's End                    302.0   
2                                           Spectre                    602.0   
3                             The Dark Knight Rises                    813.0   
4  Star Wars: Episode VII - The Force Awakens    ...                     NaN   
5                                       John Carter                    462.0   
6                                      Spider-Man 3                    392.0   
7                                           Tangled                    324.0   
8                           Avengers: Age of Ultron                    635.0   
9            Harry Potter and the Half-Blood Prince                    375.0   

  country  
0     USA  
1     USA  
2      UK  
3     USA  
4     NaN  
5     USA  
6     USA  
7     USA  
8     USA  
9      UK

12. Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields #(movie_metadata.csv file).

In [ ]:
import pandas as pd
df = pd.read_csv('movie_metadata.csv')
print("Details of the seventh movie:")
print(df[['movie_title','num_critic_for_reviews' ,'country']].iloc[6])

Details of the seventh movie:
movie_title               Spider-Man 3 
num_critic_for_reviews              392
country                             USA
Name: 6, dtype: object


13. Write a Pandas program to sort the DataFrame based on title_year from dataset of movie_metadata.csv for any particular three fields 

In [ ]:
import pandas as pd
df = pd.read_csv('movie_metadata.csv')
print("Sorted by title_year")
df[['movie_title','country','content_rating','title_year']].sort_values('title_year')

Sorted by title_year


movie_title  country  \
4810  Intolerance: Love's Struggle Throughout the Ages       USA   
4958                    Over the Hill to the Poorhouse       USA   
4885                                    The Big Parade       USA   
2734                                        Metropolis   Germany   
4812                               The Broadway Melody       USA   
...                                                 ...      ...   
4798                                Heroes                   USA   
4803                           Home Movies                   USA   
4819                            Revolution                   USA   
4869                          Happy Valley                    UK   
5039                         The Following                   USA   

     content_rating  title_year  
4810      Not Rated      1916.0  
4958            NaN      1920.0  
4885      Not Rated      1925.0  
2734      Not Rated      1927.0  
4812         Passed      1929.0  
...             ...         ...  
4798          TV-14         NaN  
4803          TV-PG         NaN  
4819          TV-14         NaN  
4869          TV-MA         NaN  
5039          TV-14         NaN  

[5043 rows x 4 columns]

14. Write a Pandas program to sort the DataFrame based on country  and language from dataset of  movie_metadata.csv

In [ ]:
import pandas as pd
df = pd.read_csv('movie_metadata.csv')
print("Sorted by country and language")
df[['movie_title','content_rating','num_user_for_reviews','content_rating','budget','title_year','country','language']].sort_values(['country','language'])

Sorted by country and language


movie_title content_rating  \
4735                                             Osama           PG-13   
4000                          The Secret in Their Eyes               R   
4415                                       Nine Queens               R   
4450                                     The Holy Girl               R   
4666                                      Live-In Maid         Unrated   
...                                                 ...            ...   
2370                      Gone, Baby, Gone                       TV-14   
3397                              Preacher                       TV-MA   
4021                                       Dawn Patrol             NaN   
4     Star Wars: Episode VII - The Force Awakens    ...            NaN   
279                            10,000 B.C.                         NaN   

     num_user_for_reviews content_rating     budget  title_year      country  \
4735                   77          PG-13    46000.0      2003.0  Afghanistan   
4000                  231              R  2000000.0      2009.0    Argentina   
4415                  125              R  1500000.0      2000.0    Argentina   
4450                   37              R  1400000.0      2004.0    Argentina   
4666                   11        Unrated   800000.0      2004.0    Argentina   
...                   ...            ...        ...         ...          ...   
2370                  NaN          TV-14        NaN         NaN          NaN   
3397                   85          TV-MA        NaN         NaN          NaN   
4021                   13            NaN  3500000.0      2014.0          NaN   
4                     NaN            NaN        NaN         NaN          NaN   
279                   NaN            NaN        NaN         NaN          NaN   

     language  
4735     Dari  
4000  Spanish  
4415  Spanish  
4450  Spanish  
4666  Spanish  
...       ...  
2370  English  
3397  English  
4021  English  
4         NaN  
279       NaN  

[5043 rows x 8 columns]

15. Write a Pandas program to get the details of the movies record number divisable by 5 of the DataFrame #(movie_metadata.csv file).

In [ ]:
import pandas as pd
df = pd.read_csv('movie_metadata.csv')
print("Details of the movies record number divisable by 5 ")
for i in range(5,5043,5):
    print(df.iloc[i],'\n')

Details of the movies record number divisable by 5 
color                                                                    Color
director_name                                                   Andrew Stanton
num_critic_for_reviews                                                     462
duration                                                                   132
director_facebook_likes                                                    475
actor_3_facebook_likes                                                     530
actor_2_name                                                   Samantha Morton
actor_1_facebook_likes                                                     640
gross                                                              7.30587e+07
genres                                                 Action|Adventure|Sci-Fi
actor_1_name                                                      Daryl Sabara
movie_title                                                       John Carter 


Name: 415, dtype: object 

color                                                                    Color
director_name                                                     Martin Brest
num_critic_for_reviews                                                      98
duration                                                                   178
director_facebook_likes                                                    102
actor_3_facebook_likes                                                     551
actor_2_name                                                         Brad Pitt
actor_1_facebook_likes                                                   12000
gross                                                              4.46063e+07
genres                                                   Drama|Fantasy|Romance
actor_1_name                                                   Anthony Hopkins
movie_title                                                    Meet Joe Black 
num_voted_users          

Name: 1365, dtype: object 

color                                                                    Color
director_name                                                       Kirk Jones
num_critic_for_reviews                                                     170
duration                                                                   110
director_facebook_likes                                                     52
actor_3_facebook_likes                                                     651
actor_2_name                                                      Dennis Quaid
actor_1_facebook_likes                                                   10000
gross                                                              4.11022e+07
genres                                                    Comedy|Drama|Romance
actor_1_name                                                     Anna Kendrick
movie_title                              What to Expect When You're Expecting 
num_voted_users         

Name: 2695, dtype: object 

color                                                                    Color
director_name                                                    Terry Gilliam
num_critic_for_reviews                                                     230
duration                                                                   142
director_facebook_likes                                                      0
actor_3_facebook_likes                                                    1000
actor_2_name                                                       Bob Hoskins
actor_1_facebook_likes                                                   22000
gross                                                                9.929e+06
genres                                                            Drama|Sci-Fi
actor_1_name                                                    Robert De Niro
movie_title                                                            Brazil 
num_voted_users         

Name: 4545, dtype: object 

color                                                                    Color
director_name                                                  Martin Scorsese
num_critic_for_reviews                                                     129
duration                                                                   122
director_facebook_likes                                                  17000
actor_3_facebook_likes                                                     184
actor_2_name                                                    Keith Richards
actor_1_facebook_likes                                                     543
gross                                                              5.35538e+06
genres                                             Biography|Documentary|Music
actor_1_name                                                       Mick Jagger
movie_title                                                     Shine a Light 
num_voted_users         

16. Write a Pandas program to find the mean and standard deviation, maximum and minimum of the data of  50 students Python marks stored in a CSV file called Python_mark.csv( you have to create the file yourself like rollno,mark for 50 records)

In [ ]:
import pandas as pd
df = pd.read_csv('Python_mark.csv')
print("Mean of the data for 50 students Python marks is",df['Marks'].mean())
print("Standard deviation of the data for 50 students Python marks is",df['Marks'].std())
print("Maximum of the data for 50 students Python marks is",df['Marks'].max())
print("Minimum of the data for 50 students Python marks is",df['Marks'].min())

Mean of the data for 50 students Python marks is 49.1
Standard deviation of the data for 50 students Python marks is 30.049109464206037
Maximum of the data for 50 students Python marks is 100
Minimum of the data for 50 students Python marks is 5


17. Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the  array and store them into a variable.

In [ ]:
import numpy as np
x = np.random.rand(4, 4)
print("Original array: ")
print(x)

print("\n2nd and 3rd rows of the above array:")
y= x[1:3]
print(y)

Original array: 
[[0.4084328  0.75771793 0.55965146 0.21729529]
 [0.07601263 0.34304034 0.67642983 0.1366053 ]
 [0.79428471 0.21127081 0.35101336 0.17694605]
 [0.78278335 0.2029585  0.85736168 0.33215805]]

2nd and 3rd rows of the above array:
[[0.07601263 0.34304034 0.67642983 0.1366053 ]
 [0.79428471 0.21127081 0.35101336 0.17694605]]


18. Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
x = np.random.rand(10, 10)
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("\nMinimum Value:",xmin,"and Maximum Value:",xmax)

Original Array:
[[0.34450862 0.6651362  0.36260805 0.40857196 0.03893626 0.59112759
  0.86862846 0.81805492 0.11220335 0.34866192]
 [0.55020103 0.89868255 0.20656367 0.1925558  0.83464274 0.70518681
  0.1512648  0.96726024 0.96834295 0.14282079]
 [0.57655786 0.11566971 0.55155528 0.27604068 0.51371813 0.92627961
  0.65372786 0.9709595  0.1960573  0.35897997]
 [0.83113195 0.99606302 0.75149867 0.38007628 0.08710185 0.84259446
  0.48635871 0.05900827 0.67468837 0.57704877]
 [0.92595368 0.47596602 0.95620368 0.207172   0.24127063 0.72558365
  0.33609161 0.13920665 0.39877527 0.84087337]
 [0.49512754 0.10587495 0.44544311 0.88594571 0.26604738 0.9216295
  0.33076355 0.28890063 0.70343273 0.03017881]
 [0.62196959 0.21981502 0.69269536 0.22883081 0.68170904 0.77394142
  0.58282372 0.11608911 0.58696745 0.64919967]
 [0.34861695 0.74514272 0.9401331  0.32398956 0.93799522 0.2923912
  0.92321852 0.4148998  0.73168811 0.74479135]
 [0.22438077 0.43838157 0.49380288 0.11974074 0.99015959 0.3011663

19. Write a NumPy program to generate 8 random integers between 100 and 300



In [ ]:
import numpy as np
x=np.random.randint(100, 300, 8)
print(x)

[254 226 207 237 203 244 269 276]


20. Write a NumPy program to create a random integer nos of size 20 and sort it.

In [ ]:
import numpy as np
x=np.arange(20)
np.random.shuffle(x)
print(x)
x.sort()
print(x)

[18  6 19  8 15 13 10 14 16 11  0  5  9 12  1  3  4  2  7 17]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
